# Generated by Django 3.0.2 on 2020-02-01 21:02

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction_wizard', '0002_auto_20200119_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnmapping',
            name='target',
            field=models.CharField(choices=[('datetime', 'Date / time'), ('account', 'Account'), ('amount', 'Amount'), ('payee', 'Payee'), ('category', 'Category'), ('text', 'Text'), ('tags', 'Tags'), ('reference', 'Reference')], max_length=255),
        ),
        migrations.CreateModel(
            name='ValueMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'value mapping',
                'verbose_name_plural': 'value mappings',
            },
        ),
    ]
