# Generated by Django 3.0.2 on 2020-02-08 11:21

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('transaction_wizard', '0003_auto_20200201_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuemapping',
            name='values',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
        migrations.AlterUniqueTogether(
            name='valuemapping',
            unique_together={('content_type', 'object_id')},
        ),
    ]
