# Generated by Django 2.2.7 on 2019-11-25 11:08

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191101_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='currency',
            new_name='balance_currency',
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='balance'),
        ),
    ]
