# Generated by Django 3.0.1 on 2019-12-30 23:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191125_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='starting balance date'),
        ),
    ]
