# Generated by Django 3.0.2 on 2020-01-18 15:36

from django.conf import settings
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('tags', '0001_initial'), ('tags', '0002_auto_20191023_1255'), ('tags', '0003_auto_20200104_1332'), ('tags', '0004_auto_20200108_1318'), ('tags', '0005_auto_20200113_0852'), ('tags', '0006_auto_20200113_1351'), ('tags', '0007_auto_20200117_2144')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django.contrib.postgres.fields.citext.CICharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='color')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='last used')),
                ('use_count', models.PositiveIntegerField(default=0, help_text='How often this tag was used. Does not decrease.', verbose_name='use count')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ('name',),
                'unique_together': {('user', 'name')},
            },
        ),
    ]
