# Generated by Django 3.0.2 on 2020-01-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20200108_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last used'),
        ),
        migrations.AddField(
            model_name='tag',
            name='use_count',
            field=models.PositiveIntegerField(default=0, help_text='How often this tag was used. Does not decrease.', verbose_name='use count'),
        ),
    ]
