# Generated by Django 3.0.2 on 2020-01-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_auto_20200113_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
    ]
