version: "3"
services:
  api:
    image: docker.pkg.github.com/julianwachholz/personal-finance/shinywaffle:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DJANGO_ENV: development
    volumes:
      - ./static:/app/static
    env_file: .env
    command: /app/config/run.sh
    ports:
      - 9066:8000
    restart: "no"
    # healthcheck:
    #   test: curl --fail http://localhost:8000/health/?format=json || exit 1
    #   interval: 1m
    #   timeout: 5s
    #   retries: 2
    #   start_period: 1m

  web:
    build:
      context: .
      dockerfile: ./DockerfileWeb
      args:
        REACT_APP_SENTRY_DSN: $SENTRY_DSN
    ports:
      - 9166:80
    restart: "no"

networks:
  default:
    external:
      name: db
