version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DJANGO_ENV: development
    volumes:
      - ./static:/app/static
    env_file: .env
    command: /app/config/run.sh
    ports:
      - 9066:8000
    restart: "no"
    # healthcheck:
    #   test: curl --fail http://localhost:8000/health/?format=json || exit 1
    #   interval: 1m
    #   timeout: 5s
    #   retries: 2
    #   start_period: 1m

  web:
    build:
      context: .
      dockerfile: ./DockerfileWeb
      target: development
      args:
        REACT_APP_SENTRY_DSN: $SENTRY_DSN
    ports:
      - 9166:3000
    restart: "no"

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
