# Generated by Django 2.2.4 on 2019-09-23 12:49

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [("categories", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
        migrations.AddField(
            model_name="category",
            name="color",
            field=colorfield.fields.ColorField(
                blank=True, max_length=18, verbose_name="color"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="is_expense",
            field=models.BooleanField(default=True, verbose_name="is an expense?"),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="categories.Category",
                verbose_name="parent",
            ),
        ),
    ]
