# Generated by Django 3.0.2 on 2020-01-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial_squashed_0005_auto_20200117_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
