# Generated by Django 2.2.5 on 2019-11-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_auto_20190923_1249"),
    ]

    operations = [
        migrations.RemoveField(model_name="category", name="is_expense",),
    ]
