# Generated by Django 2.2.5 on 2019-10-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("taxdata", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="taxbase", name="valid_from", field=models.DateField()
        )
    ]
