# Generated by Django 3.0 on 2019-12-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payee',
            name='type',
            field=models.CharField(choices=[('business', 'business'), ('private', 'private')], default='business', max_length=100, verbose_name='type'),
        ),
    ]
