# Generated by Django 3.0.1 on 2020-01-08 13:32

import django.contrib.postgres.fields.citext
from django.conf import settings
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payees", "0003_payee_default_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payee",
            options={
                "ordering": ("name",),
                "verbose_name": "payee",
                "verbose_name_plural": "payees",
            },
        ),
        CITextExtension(),
        migrations.AlterField(
            model_name="payee",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(
                max_length=100, verbose_name="name"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payee", unique_together={("user", "name")}
        ),
    ]
