# Generated by Django 3.0.2 on 2020-01-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payees', '0004_auto_20200108_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payee',
            name='type',
            field=models.CharField(choices=[('business', 'business'), ('private', 'person')], default='business', max_length=100, verbose_name='type'),
        ),
    ]
