# Generated by Django 3.0 on 2019-12-30 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedtransaction',
            name='related',
            field=models.ForeignKey(blank=True, help_text='Reverse transaction to a transfer.', null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.PlannedTransaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related',
            field=models.ForeignKey(blank=True, help_text='Reverse transaction to a transfer.', null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction'),
        ),
    ]
