# Generated by Django 3.0 on 2019-12-20 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date / time'),
        ),
    ]
