# Generated by Django 3.0.1 on 2019-12-30 22:54

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_remove_category_is_expense'),
        ('transactions', '0002_auto_20191230_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedtransaction',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plannedtransactions', to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='categories.Category'),
        ),
    ]
