# Generated by Django 3.0.1 on 2019-12-30 23:14

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_remove_category_is_expense'),
        ('payees', '0002_payee_type'),
        ('transactions', '0003_auto_20191230_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedtransaction',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plannedtransactions', to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='plannedtransaction',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plannedtransactions', to='payees.Payee'),
        ),
        migrations.AlterField(
            model_name='plannedtransaction',
            name='related',
            field=models.ForeignKey(blank=True, help_text='Reverse transaction to a transfer.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.PlannedTransaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payees.Payee'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='related',
            field=models.ForeignKey(blank=True, help_text='Reverse transaction to a transfer.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.Transaction'),
        ),
    ]
