# Generated by Django 3.0.1 on 2019-12-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20191230_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_initial',
            field=models.BooleanField(default=False, verbose_name='initial balance?'),
        ),
    ]
