# Generated by Django 3.0.2 on 2020-02-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20200119_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plannedtransaction',
            old_name='related',
            new_name='reverse_transaction',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='related',
            new_name='reverse_transaction',
        ),
        migrations.RemoveField(
            model_name='plannedtransaction',
            name='reference',
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_reconciled',
            field=models.BooleanField(default=False, verbose_name='reconciled?'),
        ),
    ]
