# Generated by Django 3.0.1 on 2020-01-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='decimal_separator',
            field=models.CharField(default='.', max_length=3, verbose_name='decimal separator'),
        ),
        migrations.AddField(
            model_name='settings',
            name='group_separator',
            field=models.CharField(default=' ', max_length=3, verbose_name='group / thousand separator'),
        ),
    ]
