# Generated by Django 3.0.1 on 2020-01-07 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20200104_1332'),
        ('settings', '0002_auto_20200103_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='default_credit_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='categories.Category'),
        ),
    ]
