# Generated by Django 3.0.2 on 2020-01-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20200117_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='language',
            field=models.CharField(default='en', max_length=10, verbose_name='language'),
        ),
    ]
