# Generated by Django 3.0.2 on 2020-01-31 12:30

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_settings_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='default_currency',
            field=djmoney.models.fields.CurrencyField(blank=True, default='USD', max_length=3),
        ),
    ]
