# Generated by Django 3.0.2 on 2020-02-02 16:57

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_auto_20200131_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='default_currency',
            field=djmoney.models.fields.CurrencyField(blank=True, default='', max_length=3),
        ),
    ]
