# Generated by Django 3.0.2 on 2020-01-17 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='target',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='target amount'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL),
        ),
    ]
