name: Build Docker image and frontend resources

on:
  push:
    branches:
      - master

jobs:
  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --tag shinywaffle:latest
